format_version: 3
pipelines:
  Home-Automation-Pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/space-bits/homeAutomation.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Test-And-Report:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-tests:
            timeout: 5
            tasks:
            - exec:
                command: npm test
                working_directory: server
                run_if: passed
